# Generated by Django 6.0.7 on 2026-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default='2007-11-18'),
            preserve_default=False,
        ),
    ]
