# Generated by Django 6.0.7 on 2026-07-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='cato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.cat'),
        ),
    ]
