# Generated by Django 6.0.7 on 2026-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to='posts/images/'),
        ),
    ]
