# Generated by Django 6.0.7 on 2026-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_pub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to='posts/images'),
        ),
    ]
